[build]
  publish = "."
  command = "echo 'Static site - no build needed'"
  ignore = "git diff --quiet HEAD^ HEAD -- . || echo changed"

[build.environment]
  NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
